aws:
  region: us-east-1

s3:
  bucket: steam-datalake-duplt

  raw_prefix: raw
  processed_prefix: processed
  analytics_prefix: analytics

  tag_endpoint: tags
  app_endpoint: apps
  content_endpoint: contents

