aws:
  region: us-east-1

s3:
  bucket: steam-datalake-duplt

  raw_prefix: raw
  tag_endpoint: tags
  app_endpoint: apps
  app_info_endpoint: app_info

  processed_prefix: processed
  analytics_prefix: analytics